# 모듈 importing

In [ ]:
import torch
import numpy as np

# 2.2 텐서 조작하기 1

## 기본 feature 비교

In [ ]:
t_np = np.array([0, 1, 2, 3, 4, 5, 6])
print(f"t_np: {t_np}")
print(f"Rank of t_np: {t_np.ndim}")
print(f"Shape of t_np: {t_np.shape}\n")

t_tensor = torch.IntTensor([0, 1, 2, 3, 4, 5, 6])
print(f"t_tensor: {t_tensor}")
print(f"Rank of t_tensor: {t_tensor.dim()}")
print(f"Shape of t_tensor: {t_tensor.shape}")

t_np: [0 1 2 3 4 5 6]
Rank of t_np: 1
Shape of t_np: (7,)

t_tensor: tensor([0, 1, 2, 3, 4, 5, 6], dtype=torch.int32)
Rank of t_tensor: 1
Shape of t_tensor: torch.Size([7])


In [ ]:
t_2d_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
    ])
print(f"t_np: {t_2d_np}")
print(f"Rank of t_np: {t_2d_np.ndim}")
print(f"Shape of t_np: {t_2d_np.shape}\n")

t_2d_torch = torch.IntTensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
    ])
print(f"t_torch: {t_2d_torch}")
print(f"Rank of t_torch: {t_2d_torch.dim()}")
print(f"Shape of t_torchr: {t_2d_torch.shape}")

t_np: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Rank of t_np: 2
Shape of t_np: (4, 3)

t_torch: tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]], dtype=torch.int32)
Rank of t_torch: 2
Shape of t_torchr: torch.Size([4, 3])


## 브로드캐스팅

In [ ]:
# Vector + scalar
m1 = torch.FloatTensor([
    [1, 2]
    ])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [ ]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([
    [1, 2]
    ])
m2 = torch.FloatTensor([
    [3],
    [4]
    ])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [ ]:
m1 = torch.FloatTensor([
    [1, 2],
    [3, 4]
    ])
m2 = torch.FloatTensor([
    [1],
    [2]
    ])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [ ]:
# element-wise multiplication에서도 broadcasting

m1 = torch.FloatTensor([
    [1, 2],
    [3, 4]
    ])
m2 = torch.FloatTensor([
    [1],
    [2]
    ])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## 기본 연산

In [ ]:
# 평균
t = torch.FloatTensor([
    [1, 2],
    [3, 4]
    ])
print(f"모든 원소의 평균: {t.mean()}")
print(f"행 방향으로(열 간) 평균: {t.mean(dim=0)}")
print(f"열 방향으로(행 간) 평균: {t.mean(dim=1)}")

모든 원소의 평균: 2.5
행 방향으로(열 간) 평균: tensor([2., 3.])
열 방향으로(행 간) 평균: tensor([1.5000, 3.5000])


In [ ]:
# 덧셈
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [ ]:
# 최대
print(t.max()) # Returns one value: max
print(t.max(dim=0), end="\n\n") # Returns two values: max and argmax
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1], end="\n\n")
print(t.max(dim=1))
print(t.max(dim=-1))

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


# 2.3 텐서 조작하기 2

## 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경. 매우 중요!
---
넘파이 reshape와 같은 역할

In [ ]:
t = np.array([
    [[0, 1, 2, 3],
     [4, 5, 6, 7],
     [8, 9, 10, 11]],
    [[12, 13, 14, 15],
     [16, 17, 18, 19],
     [20, 21, 22, 23]]
    ])
ft = torch.FloatTensor(t)
ft_shape = ft.shape
print(ft_shape)

ptr = 0
mem_address = []
for i in range(ft_shape[0]):
  for j in range(ft_shape[1]):
    for k in range(ft_shape[2]):
      if ptr != 0:
        print(f"[{i}][{j}][{k}] memory size: {ft[i][j][k].data_ptr() - ptr}")
      ptr = ft[i][j][k].data_ptr()
      mem_address.append(ptr)

torch.Size([2, 3, 4])
[0][0][1] memory size: 4
[0][0][2] memory size: 4
[0][0][3] memory size: 4
[0][1][0] memory size: 4
[0][1][1] memory size: 4
[0][1][2] memory size: 4
[0][1][3] memory size: 4
[0][2][0] memory size: 4
[0][2][1] memory size: 4
[0][2][2] memory size: 4
[0][2][3] memory size: 4
[1][0][0] memory size: 4
[1][0][1] memory size: 4
[1][0][2] memory size: 4
[1][0][3] memory size: 4
[1][1][0] memory size: 4
[1][1][1] memory size: 4
[1][1][2] memory size: 4
[1][1][3] memory size: 4
[1][2][0] memory size: 4
[1][2][1] memory size: 4
[1][2][2] memory size: 4
[1][2][3] memory size: 4


3D &rarr; 2D

In [ ]:
reshape_ft = ft.view([-1, 3]) # ft라는 텐서를 (?, 3)의 크기로 변경
print(reshape_ft)
reshape_ft_shape = reshape_ft.shape
print(reshape_ft_shape, end="\n\n")

ptr = 0
reshape_mem_address = []
for i in range(reshape_ft_shape[0]):
  for j in range(reshape_ft_shape[1]):
    if ptr != 0:
      print(f"[{i}][{j}] memory size: {reshape_ft[i][j].data_ptr() - ptr}")
    ptr = reshape_ft[i][j].data_ptr()
    reshape_mem_address.append(ptr)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]])
torch.Size([8, 3])

[0][1] memory size: 4
[0][2] memory size: 4
[1][0] memory size: 4
[1][1] memory size: 4
[1][2] memory size: 4
[2][0] memory size: 4
[2][1] memory size: 4
[2][2] memory size: 4
[3][0] memory size: 4
[3][1] memory size: 4
[3][2] memory size: 4
[4][0] memory size: 4
[4][1] memory size: 4
[4][2] memory size: 4
[5][0] memory size: 4
[5][1] memory size: 4
[5][2] memory size: 4
[6][0] memory size: 4
[6][1] memory size: 4
[6][2] memory size: 4
[7][0] memory size: 4
[7][1] memory size: 4
[7][2] memory size: 4


In [ ]:
for i, add in enumerate(mem_address):
  if reshape_mem_address[i] != add:
    tmp = reshape_mem_address[i]
    print(f"index: {i}, ft address: {hex(add)}, reshape address: {hex(tmp)}")
  else:
    print(f"address: {hex(add)}")

address: 0x556d1543dc40
address: 0x556d1543dc44
address: 0x556d1543dc48
address: 0x556d1543dc4c
address: 0x556d1543dc50
address: 0x556d1543dc54
address: 0x556d1543dc58
address: 0x556d1543dc5c
address: 0x556d1543dc60
address: 0x556d1543dc64
address: 0x556d1543dc68
address: 0x556d1543dc6c
address: 0x556d1543dc70
address: 0x556d1543dc74
address: 0x556d1543dc78
address: 0x556d1543dc7c
address: 0x556d1543dc80
address: 0x556d1543dc84
address: 0x556d1543dc88
address: 0x556d1543dc8c
address: 0x556d1543dc90
address: 0x556d1543dc94
address: 0x556d1543dc98
address: 0x556d1543dc9c


3D &rarr; 3D

In [ ]:
print(ft.view([-1, 2, 3]))
print(ft.view([-1, 2, 3]).shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]],

        [[12., 13., 14.],
         [15., 16., 17.]],

        [[18., 19., 20.],
         [21., 22., 23.]]])
torch.Size([4, 2, 3])


## 스퀴즈 & 언스퀴즈
---
* 스퀴즈(Squeeze) - 1인 차원을 제거
* 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가

In [ ]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape, end="\n\n")
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])

tensor([0., 1., 2.])
torch.Size([3])


In [ ]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape, end="\n\n")
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape, end="\n\n")

ft = torch.Tensor([0, 1, 2])
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

torch.Size([3])

tensor([[0., 1., 2.]])
torch.Size([1, 3])

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
ft = torch.Tensor([0, 1, 2])
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
ft = torch.Tensor([0, 1, 2])
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## 타입 캐스팅

In [ ]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [ ]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## concatenate & stack
---
* concatenate: 일정 방향으로 텐서를 연장
* stack: 차원 증가하는 방향으로 텐서를 연장

In [ ]:
x = torch.FloatTensor([
    [1, 2],
    [3, 4]
    ])
y = torch.FloatTensor([
    [5, 6],
    [7, 8]
    ])
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [ ]:
print(torch.stack([x, y]))
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0)], dim=0)) # 전부 1x2 Tensor로 만들고 column 방향으로 확장
print(torch.stack([x, y], dim=1))

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[[1., 2.],
         [5., 6.]],

        [[3., 4.],
         [7., 8.]]])


## ones_like & zeros_like

In [ ]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 덮어쓰기 연산
+=, -=, *=, /=

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x, end="\n\n") # 기존의 값 출력
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


# 2.4 파이썬 클래스
---
## 클래스로 디자인 하는 이유
1. 캡슐화
2. 연산자 오버로딩
3. 동작에 집중
4. 추상화에 유리